### ISSUE TITLE
Probleme mit NumberOfUpdates JDBC-Adapter

### ISSUE THREAD

**Issue by SvenRop** [citrusframework/citrus-db#30]
Hallo,
wir haben Probleme mit dem NumberOfUpdates nach einem SQL-Update-Aufruf.

Es werden standardmäßig als NumberOfUpdates 0 zurückgegeben.

Können wir hier selbst etwas anpassen oder liegt das bei euch?  Wir prüfen in unserem Programm genau diesen Fall und laufen dadurch immerwieder auf Fehler.

Viele Grüße
Sven

**Comment by svettwer** [comment]
Closed due to inactivity
